CREATE TABLE urls (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code   VARCHAR(16)  NOT NULL UNIQUE,  -- base62(id); 11 chars covers the full BIGINT range
    long_url     TEXT         NOT NULL,
    user_id      BIGINT,                        -- nullable until auth exists; FK to users added later
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ,                   -- NULL = never expires
    click_count  BIGINT       NOT NULL DEFAULT 0
);
